stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/process

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/process
    - src/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/feature_eng

  model_building:
    cmd: python src/model_building.py
    deps:
    - data/feature_eng
    - src/model_building.py
    params:
    - model_building.learning_rate 
    - model_building.n_estimators
    outs:
    - model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - model.pkl
    - src/model_evaluation.py
    metrics:
    - metrics.json
